-- Seeds the service catalog from the Prudence Advisory brochure.
-- Run via `supabase db reset` (auto) or `psql -f supabase/seed.sql`.

insert into public.service_catalog (pillar, category, name, sort_order) values
-- NRI Services
('nri', 'Taxation & Compliance', 'Income Tax Return Filing for NRIs', 1),
('nri', 'Taxation & Compliance', 'DTAA Advisory and Tax Relief Claims', 2),
('nri', 'Taxation & Compliance', 'Lower / Nil TDS Certificate (Form 13)', 3),
('nri', 'Taxation & Compliance', 'Capital Gains Tax Planning on Property Sale', 4),
('nri', 'Banking, FEMA & Repatriation', 'FEMA and RBI Compliance Advisory', 5),
('nri', 'Banking, FEMA & Repatriation', 'NRO / NRE / FCNR Account Advisory', 6),
('nri', 'Banking, FEMA & Repatriation', 'Repatriation of Funds (Form 15CA / 15CB)', 7),
('nri', 'Investments, Property & Business', 'Investment Advisory (Equity, Mutual Funds, Real Estate)', 8),
('nri', 'Investments, Property & Business', 'NRI Property Management and Compliance', 9),
('nri', 'Investments, Property & Business', 'Business / Liaison / Branch Office / Subsidiary Setup', 10),
('nri', 'Personal, Estate & Concierge', 'PAN, Aadhaar, and OCI Assistance', 11),
('nri', 'Personal, Estate & Concierge', 'Inheritance and Succession Planning', 12),
('nri', 'Personal, Estate & Concierge', 'Power of Attorney Drafting and Execution', 13),
('nri', 'Personal, Estate & Concierge', 'Premium Concierge (Elder Care, Medical, Events)', 14),
-- Family Business Services
('family_business', 'Governance', 'Family Constitution and Charter Drafting', 1),
('family_business', 'Governance', 'Family Governance Framework Design', 2),
('family_business', 'Governance', 'Conflict Resolution and Mediation', 3),
('family_business', 'Succession & Estate', 'Succession and Estate Planning', 4),
('family_business', 'Succession & Estate', 'Will Drafting and Execution Support', 5),
('family_business', 'Succession & Estate', 'Private Family Trust Formation', 6),
('family_business', 'Succession & Estate', 'Inter-Generational Wealth Transfer', 7),
('family_business', 'Wealth & Family Office', 'Family Office Set-Up and Management', 8),
('family_business', 'Wealth & Family Office', 'Wealth Structuring and Asset Protection', 9),
('family_business', 'Wealth & Family Office', 'Philanthropy and CSR Advisory', 10),
('family_business', 'Business Structuring', 'Business Restructuring and Demerger', 11),
('family_business', 'Business Structuring', 'Holding Company Structuring', 12),
('family_business', 'Business Structuring', 'Family Business Valuation', 13),
('family_business', 'Business Structuring', 'Next-Generation Mentoring and Onboarding', 14),
-- Accounting, CFO & Advisory Services
('accounting_cfo', 'Accounting & Bookkeeping', 'Bookkeeping and Accounting Services', 1),
('accounting_cfo', 'Accounting & Bookkeeping', 'Payroll Processing and Compliance', 2),
('accounting_cfo', 'Accounting & Bookkeeping', 'MIS Reporting and Financial Analysis', 3),
('accounting_cfo', 'Audit & Assurance', 'Statutory Audit and Assurance', 4),
('accounting_cfo', 'Audit & Assurance', 'Internal and Management Audit', 5),
('accounting_cfo', 'Audit & Assurance', 'Tax Audit under Section 44AB', 6),
('accounting_cfo', 'Tax & Regulatory', 'Direct Tax Advisory and Compliance', 7),
('accounting_cfo', 'Tax & Regulatory', 'GST Registration, Returns, and Advisory', 8),
('accounting_cfo', 'Tax & Regulatory', 'TDS Compliance and Filing', 9),
('accounting_cfo', 'Tax & Regulatory', 'Transfer Pricing Advisory', 10),
('accounting_cfo', 'Corporate, CFO & Transactions', 'ROC and Secretarial Compliance / Incorporation', 11),
('accounting_cfo', 'Corporate, CFO & Transactions', 'Virtual and Fractional CFO Services', 12),
('accounting_cfo', 'Corporate, CFO & Transactions', 'Due Diligence and Transaction Advisory', 13),
('accounting_cfo', 'Corporate, CFO & Transactions', 'Procurement Outsourcing; Policy and Process Design', 14);
